БД
NikolayARV/bd pull request #1
Opened 2023-05-16 18:50 UTC by NikolayARV

2023-05-16 20:12 UTC, OlgaLugacheva requested changes

2023-05-16 20:12 UTC, OlgaLugacheva commented on mvnw
> +#!/bin/sh
это в игнор

2023-05-16 20:12 UTC, OlgaLugacheva commented on src/main/java/com/example/ru/hogwarts/school/controller/HouseController.java
> +public interface HouseController {
ну интерфейс конечно можно, но если у нас автогенация на основе openapi а так несколько лишнее это все же

2023-05-16 20:12 UTC, OlgaLugacheva commented on src/main/java/com/example/ru/hogwarts/school/controller/HouseController.java
> +    @PutMapping
put тоже по id

2023-05-16 20:12 UTC, OlgaLugacheva commented on src/main/java/com/example/ru/hogwarts/school/controller/HouseController.java
> +    @GetMapping("{color}")
цвет лучше параметром

2023-05-16 20:12 UTC, OlgaLugacheva commented on src/main/java/com/example/ru/hogwarts/school/controller/HouseControllerImpl.java
> +public class HouseControllerImpl implements HouseController {
интерфейс лучше убрать и смотри замечания по маппингу выше

2023-05-16 20:12 UTC, OlgaLugacheva commented on src/main/java/com/example/ru/hogwarts/school/model/Student.java
> +    String name;
что-то с форматированием

2023-05-17 08:41 UTC, NikolayARV commented on mvnw
> +#!/bin/sh
Для этого файла почему-то не активна функция Add to gitignore.

2023-05-17 19:01 UTC, OlgaLugacheva requested changes

2023-05-17 19:01 UTC, OlgaLugacheva commented on src/main/java/com/example/ru/hogwarts/school/controller/StudentControllerImpl.java
> +public class StudentControllerImpl {
Impl можно убрать

2023-05-17 19:01 UTC, OlgaLugacheva commented on src/main/java/com/example/ru/hogwarts/school/controller/HouseControllerImpl.java
> +public class HouseControllerImpl  {
Impl можно убрать

2023-05-18 07:55 UTC, merged